name: fast_share
description: Fast Share is a clean Flutter P2P file transfer app with QR join, chunked sockets, PC downloads, and smart cleanup.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  archive: ^4.0.9
  camera: ^0.11.2+1
  cryptography: ^2.9.0
  crypto: ^3.0.7
  file_picker: ^10.1.9
  flutter_local_notifications: ^19.4.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.0
  mime: ^2.0.0
  mobile_scanner: ^6.0.7
  google_mobile_ads: ^5.3.0
  nearby_connections: ^4.3.0
  open_filex: ^4.7.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  provider: ^6.1.5
  qr_flutter: ^4.1.0
  sensors_plus: ^6.1.1
  shared_preferences: ^2.3.4
  url_launcher: ^6.3.1
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon/fast_share_icon.svg
    - assets/icon/fast_share_icon.png
    - assets/sounds/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/icon/fast_share_icon.png
  adaptive_icon_background: '#000000'
  adaptive_icon_foreground: assets/icon/fast_share_icon.png
  min_sdk_android: 23
