name: Build Fast Share APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17' # الإصدار الأكثر استقراراً لبناء تطبيقات أندرويد حالياً

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          # سيقوم تلقائياً بتحميل أحدث نسخة مستقرة تتوافق مع SDK 3.9.0+

      - name: Install dependencies
        run: flutter pub get

      - name: Generate Launcher Icons
        run: flutter pub run flutter_launcher_icons

      - name: Build APK
        run: flutter build apk --release --no-tree-shake-icons
        # أضفت no-tree-shake-icons لتجنب مشاكل أيقونات الـ SVG أو الأيقونات المخصصة

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: FastShare-App-Release
          path: build/app/outputs/flutter-apk/app-release.apk
